theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
auto-format = true
mouse = false
auto-save = true
bufferline = "multiple"
true-color = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

