[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }
emmet-ls = { command = "emmet-ls", args = ["--stdio"] }
phpactor = { command = "phpactor", args = ["language-server"] }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server" }, "biome" ]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "test.js"] } # file name is needed it to work
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server" }, "biome" ]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "test.js"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server" }, "biome" ]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "test.js"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ { name = "typescript-language-server" }, "biome" ]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "test.js"] }
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server" }, "biome" ]


[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-ls"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "emmet-ls"]

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls"]
# formatter = {command = "dprint", args = ["fmt", "--stdin", "md"]}
# auto-format = true
soft-wrap.enable = true

[[language]]
name = "bash"
language-servers = ["bash-language-server"]

[[language]]
name = "php"
language-servers = ["phpactor"]

[[language]]
name = "python"
language-servers = ["pylsp"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "nix"
auto-format = true
formatter.command = "alejandra"
language-servers = ["nil"]
